import type { TemplateConfig } from '@/features/template/types';

const COMMON_SIZE_OPTIONS = ['1:1', '4:5', '16:9', '9:16'];

export const TEMPLATE_CONFIGS: TemplateConfig[] = [
  {
    key: 'sns_marketing',
    title: 'SNS/마케팅광고 소재',
    comment:
      '브랜드 캠페인, 프로모션 등 마케팅 목적의 SNS피드, 배너, 썸네일 등 즉시 활용 가능한 광고 소재 생성',
    icon: '📢',
    aiStatus: 'available',
    aiFeature: 'key-visual',
    fields: [
      { key: 'source_image', label: '이미지', type: 'file', required: true },
      {
        key: 'target_audience',
        label: '타겟설정',
        type: 'tags',
        required: true,
        maxItems: 5,
      },
      {
        key: 'feedback',
        label: '마케팅 피드백',
        type: 'textarea',
        required: true,
        placeholder: '전달하고 싶은 핵심 메시지를 입력해 주세요.',
      },
      {
        key: 'concept',
        label: '컨셉',
        type: 'textarea',
        placeholder: '톤앤매너, 무드, 연출 포인트를 입력해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
      { key: 'reference_image', label: '레퍼런스', type: 'file' },
    ],
  },
  {
    key: 'detail_catalog',
    title: '상세페이지/카탈로그 생성',
    comment: '제품 배치, 공간 연출 등 실제 사용 환경을 표현한 상세 이미지 생성',
    icon: '🎨',
    aiStatus: 'available',
    aiFeature: 'detail-cut',
    fields: [
      {
        key: 'source_images',
        label: '제품 이미지(복수)',
        type: 'files',
        required: true,
      },
      {
        key: 'product_name',
        label: '제품명',
        type: 'text',
        required: true,
        placeholder: '예: 밴쿠버 소파',
      },
      {
        key: 'target_angle',
        label: '목표 각도',
        type: 'select',
        required: true,
        options: ['Front view', 'Side view', 'Top view', 'Three-quarter view'],
      },
      {
        key: 'source_angles',
        label: '원본 각도 설명',
        type: 'textarea',
        placeholder: '각 이미지 각도를 줄바꿈으로 입력해 주세요.',
      },
      {
        key: 'usage_scene',
        label: '사용 장면',
        type: 'textarea',
        placeholder: '예: 미니멀 거실, 자연광, 우드톤',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'studio_shot',
    title: '스튜디오 촬영 이미지 생성',
    comment:
      '패션, 화장품, 가구, 가전 등 제품군에 최적화된 고품질 촬영 연출 이미지 생성',
    icon: '📸',
    aiStatus: 'available',
    aiFeature: 'key-visual',
    fields: [
      {
        key: 'source_image',
        label: '제품 이미지',
        type: 'file',
        required: true,
      },
      { key: 'product_name', label: '제품명', type: 'text', required: true },
      {
        key: 'lighting',
        label: '조명 스타일',
        type: 'select',
        options: ['Softbox', 'Hard Light', 'Natural Light', 'Back Light'],
      },
      {
        key: 'background_style',
        label: '배경 스타일',
        type: 'text',
        placeholder: '예: 라이트 그레이 무광 배경',
      },
      {
        key: 'feedback',
        label: '연출 지시',
        type: 'textarea',
        required: true,
        placeholder: '카메라 앵글, 질감 강조, 분위기 등을 입력해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'multilingual',
    title: '다국어 변환 이미지 생성',
    comment: '하나의 콘텐츠를 문맥에 맞는 여러 언어로 이미지를 자동 변환',
    icon: '🌐',
    aiStatus: 'available',
    aiFeature: 'multilingual',
    fields: [
      {
        key: 'source_image',
        label: '원본 이미지',
        type: 'file',
        required: true,
      },
      {
        key: 'source_lang',
        label: '원본 언어',
        type: 'select',
        required: true,
        options: ['Korean', 'English', 'Japanese', 'Chinese'],
      },
      {
        key: 'target_lang',
        label: '대상 언어',
        type: 'select',
        required: true,
        options: ['English', 'Japanese', 'Chinese', 'Spanish'],
      },
      {
        key: 'translation_tone',
        label: '번역 톤',
        type: 'text',
        placeholder: '예: 공식적, 친근한, 럭셔리',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'infographic',
    title: '인포그래픽 이미지 생성',
    comment:
      '제품 설명, 홍보물, 분석 리포트 등 중요 정보를 시각화한 이미지 생성',
    icon: '📊',
    aiStatus: 'planned',
    aiFeature: 'planned',
    fields: [
      {
        key: 'topic',
        label: '주제',
        type: 'text',
        required: true,
        placeholder: '예: 2026 상반기 매출 분석',
      },
      {
        key: 'key_metrics',
        label: '핵심 지표',
        type: 'textarea',
        required: true,
        placeholder: '지표명을 줄바꿈으로 입력해 주세요.',
      },
      { key: 'target_audience', label: '대상 독자', type: 'tags', maxItems: 5 },
      {
        key: 'visual_tone',
        label: '비주얼 톤',
        type: 'text',
        placeholder: '예: 신뢰감 있는 B2B 리포트 스타일',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'illustration',
    title: '삽화 이미지 생성',
    comment:
      '뉴스, 웹소설 등 텍스트 기반 콘텐츠의 주제와 문맥을 시각화한 대표 이미지 생성',
    icon: '📰',
    aiStatus: 'planned',
    aiFeature: 'planned',
    fields: [
      {
        key: 'source_text',
        label: '원문 텍스트',
        type: 'textarea',
        required: true,
        placeholder: '기사/본문 핵심 내용을 붙여넣어 주세요.',
      },
      {
        key: 'genre',
        label: '장르',
        type: 'select',
        options: ['뉴스', '에세이', '웹소설', '브랜드 스토리'],
      },
      {
        key: 'mood',
        label: '분위기',
        type: 'text',
        placeholder: '예: 긴장감, 따뜻함, 희망적',
      },
      {
        key: 'style_reference',
        label: '스타일 레퍼런스',
        type: 'textarea',
        placeholder: '원하는 일러스트 스타일을 설명해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'illustration_finish',
    title: '일러스트 이미지 완성',
    comment:
      '의뢰 디자인, 웹툰(콘텐츠) 스케치 등의 이미지를 기반으로 채색·완성된 일러스트로 변환',
    icon: '🖌️',
    aiStatus: 'planned',
    aiFeature: 'planned',
    fields: [
      {
        key: 'sketch_image',
        label: '스케치 이미지',
        type: 'file',
        required: true,
      },
      {
        key: 'color_style',
        label: '채색 스타일',
        type: 'text',
        required: true,
        placeholder: '예: 셀 셰이딩, 수채화, 반실사',
      },
      {
        key: 'line_preserve',
        label: '선화 보존 수준',
        type: 'select',
        options: ['높음', '중간', '낮음'],
      },
      {
        key: 'feedback',
        label: '보정 지시',
        type: 'textarea',
        placeholder: '질감, 그림자, 디테일 보강 요청을 입력해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'size',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
];

export const TARGET_KEYWORDS = [
  '10대',
  '20대',
  '30대',
  '40대',
  '50대',
  '자기관리',
  '메이크업',
  '학생',
  '직장인',
  '신혼',
  '자취',
  '사회초년',
  '인테리어',
  '여행',
  '재테크',
  '1인가구',
  '반려동물',
  '집밥',
  '자기계발',
  '가성비',
];

export const DEFAULT_TEMPLATE_KEY = 'sns_marketing';
