import template_art from '@/assets/template_art.png';
import template_detail from '@/assets/template_detail.png';
import template_illustration from '@/assets/template_illustration.png';
import template_infographic from '@/assets/template_infographic.png';
import template_marketing from '@/assets/template_marketing.png';
import template_studio from '@/assets/template_studio.png';
import template_translation from '@/assets/template_translation.png';
import { PLATFORM_OPTIONS } from '@/features/template/constants/platformGuides';
import { COMMON_SIZE_RATIOS } from '@/features/template/constants/sizeOptions';
import type { TemplateConfig } from '@/features/template/types';

const COMMON_SIZE_OPTIONS = COMMON_SIZE_RATIOS;

export const TEMPLATE_CONFIGS: TemplateConfig[] = [
  {
    key: 'sns_marketing',
    title: 'SNS 마케팅 광고',
    comment:
      '캠페인 및 프로모션 등 마케팅 목적의 SNS 피드, 배너 등 활용 가능한 광고 소재 생성',
    imgSrc: template_marketing,
    aiStatus: 'available',
    aiFeature: 'key-visual',
    isLike: true,
    fields: [
      {
        key: 'source_image',
        label: '타겟 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'product_name',
        label: '제품명',
        type: 'text',
        required: true,
        placeholder: '브랜딩할 제품명을 입력핵주세요.',
      },
      {
        key: 'platform',
        label: '업로드 매체',
        type: 'select',
        required: true,
        options: PLATFORM_OPTIONS,
      },
      {
        key: 'target_audience',
        label: '타겟 고객층',
        type: 'tags',
        required: true,
        maxItems: 5,
      },
      {
        key: 'copy_text_enabled',
        label: '카피 문구',
        type: 'toggle',
        defaultValue: 'false',
      },
      {
        key: 'copy_text',
        label: '',
        type: 'textarea',
        placeholder: '이미지에 넣을 카피 문구를 입력해 주세요.',
        showWhen: { key: 'copy_text_enabled', value: 'true' },
      },
      {
        key: 'feedback',
        label: '핵심 메시지',
        type: 'textarea',
        required: true,
        placeholder: '전달하고 싶은 핵심 메시지를 입력해 주세요.',
      },
      {
        key: 'concept',
        label: '컨셉',
        type: 'textarea',
        placeholder: '톤앤매너, 무드, 연출 포인트를 입력해 주세요.',
      },
      {
        key: 'brand_color',
        label: '브랜드 컬러',
        type: 'text',
        placeholder: '예: #FF0000',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
      { key: 'reference_image', label: '레퍼런스', type: 'file' },
    ],
  },
  {
    key: 'detail_catalog',
    title: '상세페이지',
    comment:
      '제품 배치 및 공간 연출을 통해 실제 사용 환경을 표현한 상세 이미지 생성',
    imgSrc: template_detail,
    aiStatus: 'available',
    aiFeature: 'detail-cut',
    isLike: true,
    fields: [
      {
        key: 'source_images',
        label: '타겟 이미지',
        type: 'files',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'product_name',
        label: '제품명',
        type: 'text',
        required: true,
        placeholder: '예: 밴쿠버 소파',
      },
      {
        key: 'product_category',
        label: '제품 카테고리',
        type: 'select',
        options: ['가구', '패션', '화장품', '가전', '식품', '기타'],
      },
      {
        key: 'target_angle',
        label: '목표 각도',
        type: 'select',
        required: true,
        options: ['정면', '측면', '위에서', '사분면'],
      },
      {
        key: 'source_angles',
        label: '원본 각도 설명',
        type: 'textarea',
        placeholder:
          '업로드한 순서대로 각도를 입력해 주세요.\n예:\n1번 - 정면\n2번 - 측면',
      },
      {
        key: 'style_mood',
        label: '스타일/무드',
        type: 'select',
        options: ['미니멀', '프리미엄', '자연친화적', '트렌디', '클래식'],
      },
      {
        key: 'usage_scene',
        label: '사용 장면',
        type: 'textarea',
        placeholder: '예: 미니멀 거실, 자연광, 우드톤',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'studio_shot',
    title: '스튜디오 촬영',
    comment:
      '패션, 화장품, 가구, 가전 등 제품군에 대해 고품질 촬영 연출 이미지 생성',
    imgSrc: template_studio,
    aiStatus: 'available',
    aiFeature: 'key-visual',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '타겟 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'product_name',
        label: '제품명',
        type: 'text',
        required: true,
        placeholder: '예: 벤쿠버 소파',
      },
      {
        key: 'product_category',
        label: '제품 카테고리',
        type: 'select',
        options: ['가구', '패션', '화장품', '가전', '식품', '기타'],
      },
      {
        key: 'shoot_purpose',
        label: '촬영 목적',
        type: 'select',
        options: ['상세페이지', 'SNS', '카탈로그', '광고배너'],
      },
      {
        key: 'lighting',
        label: '조명 스타일',
        type: 'select',
        options: ['소프트박스', '하드 라이트', '자연광', '역광'],
      },
      {
        key: 'background_style',
        label: '배경 스타일',
        type: 'select',
        options: [
          '순백/무광',
          '그레이/무광',
          '블랙/무광',
          '그라데이션',
          '자연/야외',
        ],
      },
      {
        key: 'prop_style',
        label: '소품 연출',
        type: 'select',
        options: ['소품 없음', '자연소재 소품', '라이프스타일 연출'],
      },
      {
        key: 'feedback',
        label: '연출 지시',
        type: 'textarea',
        required: true,
        placeholder: '카메라 앵글, 질감 강조, 분위기 등을 입력해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'multilingual',
    title: '다국어 변환',
    comment: '하나의 콘텐츠를 문맥에 맞는 다양한 언어의 이미지를 자동 변환',
    imgSrc: template_translation,
    aiStatus: 'available',
    aiFeature: 'multilingual',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '타겟 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'source_lang',
        label: '원본 언어',
        type: 'select',
        required: true,
        options: ['한국어', '영어', '일본어', '중국어'],
      },
      {
        key: 'target_lang',
        label: '대상 언어',
        type: 'select',
        required: true,
        options: ['영어', '일본어', '중국어', '스페인어', '한국어'],
      },
      {
        key: 'target_country',
        label: '타겟 국가',
        type: 'select',
        options: ['미국', '일본', '중국', '동남아', '유럽'],
      },
      {
        key: 'translation_tone',
        label: '번역 톤',
        type: 'select',
        options: ['공식적', '친근한', '럭셔리', '세련된', '캐주얼'],
      },
      {
        key: 'brand_terms',
        label: '번역 제외 고유명사',
        type: 'tags',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'brand_layout',
    title: '브랜드 레이아웃',
    comment:
      '브랜드 레이아웃 템플릿에 맞춰 카피 포인트와 타겟 고객을 반영한 상세페이지 이미지를 생성합니다.',
    imgSrc: template_detail,
    aiStatus: 'available',
    aiFeature: 'brand-layout',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '제품 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'brand_name',
        label: '브랜드명',
        type: 'text',
        required: true,
        placeholder: '예: LANEIGE',
      },
      {
        key: 'brand_layout_template',
        label: '레이아웃 템플릿',
        type: 'select',
        required: true,
        options: [
          '2단 그리드',
          '전면 비주얼',
          '텍스트 중심',
          '제품 클로즈업',
          '라이프스타일',
        ],
      },
      {
        key: 'headline',
        label: '메인 헤드라인',
        type: 'text',
        placeholder: '예: 365일 보습, 피부가 달라집니다',
      },
      {
        key: 'copy_points',
        label: '카피 포인트',
        type: 'tags',
        required: true,
        maxItems: 5,
      },
      {
        key: 'brand_color',
        label: '브랜드 컬러',
        type: 'text',
        placeholder: '예: #0066CC',
      },
      {
        key: 'target_persona',
        label: '타겟 고객',
        type: 'text',
        required: true,
        placeholder: '예: 30대 인테리어 관심 여성',
      },
    ],
  },
  {
    key: 'lookbook',
    title: 'AI 룩북',
    comment:
      '선택한 제품 조합을 실제 공간에 배치한 카탈로그 이미지를 자동 생성합니다.',
    imgSrc: template_detail,
    aiStatus: 'available',
    aiFeature: 'lookbook',
    isLike: false,
    fields: [
      {
        key: 'source_images',
        label: '제품 이미지',
        type: 'files',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'space_style',
        label: '공간 스타일',
        type: 'select',
        required: true,
        options: ['거실', '침실', '사무실', '야외/테라스', '주방'],
        withRef: true,
      },
      {
        key: 'style_tone',
        label: '스타일 톤',
        type: 'select',
        required: true,
        options: ['모던', '내추럴', '럭셔리', '캐주얼', '미니멀'],
      },
      {
        key: 'season',
        label: '시즌',
        type: 'select',
        options: ['봄/여름', '가을/겨울', '올시즌'],
      },
      {
        key: 'concept',
        label: '룩북 컨셉',
        type: 'textarea',
        placeholder: '예: 북유럽 감성의 홈오피스, 자연 소재와 따뜻한 톤',
        withRef: true,
      },
      {
        key: 'product_labels',
        label: '제품 레이블',
        type: 'tags',
        maxItems: 6,
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'multichannel_convert',
    title: '멀티채널 변환',
    comment:
      '하나의 소재를 SNS 피드, 스토리, 배너, 썸네일 등 다양한 채널 포맷으로 자동 변환합니다.',
    imgSrc: template_marketing,
    aiStatus: 'available',
    aiFeature: 'multichannel',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '원본 소재',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'brand_name',
        label: '브랜드명',
        type: 'text',
        placeholder: '예: LANEIGE',
      },
      {
        key: 'source_copy',
        label: '원본 카피',
        type: 'textarea',
        placeholder: '이미지에 포함된 카피 텍스트를 입력해 주세요. (선택)',
      },
      {
        key: 'target_formats',
        label: '변환 채널',
        type: 'channel_select',
        required: true,
      },
      {
        key: 'copy_modify',
        label: '채널별 카피 자동 변환',
        type: 'toggle',
        defaultValue: 'true',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'campaign_content',
    title: '캠페인 콘텐츠',
    comment:
      '페르소나와 핵심 소구 포인트에 맞는 캠페인 콘셉트로 제품·배경을 조합한 마케팅 이미지를 생성합니다.',
    imgSrc: template_marketing,
    aiStatus: 'available',
    aiFeature: 'campaign',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '제품 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'product_name',
        label: '제품명',
        type: 'text',
        required: true,
        placeholder: '예: 에너지 드링크 제로',
      },
      {
        key: 'persona',
        label: '타겟 페르소나',
        type: 'text',
        required: true,
        placeholder: '예: 30대 직장인 여성, 건강에 관심 많음',
      },
      {
        key: 'appeal_points',
        label: '핵심 소구 포인트',
        type: 'tags',
        required: true,
        maxItems: 5,
      },
      {
        key: 'background_style',
        label: '배경 스타일',
        type: 'select',
        required: true,
        options: ['야외/자연', '스튜디오', '라이프스타일', '미니멀'],
      },
      {
        key: 'campaign_concept',
        label: '캠페인 콘셉트',
        type: 'textarea',
        placeholder: '캠페인 방향성이나 분위기를 입력해 주세요.',
      },
      {
        key: 'cta_text',
        label: 'CTA 문구',
        type: 'text',
        placeholder: '예: 지금 구매하기, 자세히 보기',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'persona_variants',
    title: '무한 페르소나',
    comment:
      '동일 제품에 대해 타겟 페르소나별로 성격이 완전히 다른 광고 소재를 생성합니다. A/B 테스트 세트 자동 구성.',
    imgSrc: template_marketing,
    aiStatus: 'available',
    aiFeature: 'persona-variants',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '제품 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'product_info',
        label: '제품 정보',
        type: 'textarea',
        required: true,
        placeholder: '제품명, 주요 특징 등을 입력해 주세요.',
      },
      {
        key: 'marketing_goal',
        label: '마케팅 목표',
        type: 'select',
        required: true,
        options: ['인지도', '전환', '참여'],
      },
      {
        key: 'personas',
        label: '타겟 페르소나',
        type: 'tags',
        required: true,
        maxItems: 4,
      },
      {
        key: 'output_count',
        label: '생성 수',
        type: 'select',
        options: ['2개', '3개', '4개'],
      },
      {
        key: 'channel',
        label: '활용 채널',
        type: 'select',
        options: ['인스타그램', '페이스북', '유튜브', '이메일'],
      },
    ],
  },
  {
    key: 'cross_sell_styling',
    title: 'Cross-Sell 스타일링',
    comment:
      '복수의 상품 이미지를 조합해 자연스러운 코디/스타일링 이미지를 AI로 생성합니다.',
    imgSrc: template_studio,
    aiStatus: 'available',
    aiFeature: 'cross-sell',
    isLike: false,
    fields: [
      {
        key: 'source_images',
        label: '상품 이미지',
        type: 'files',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'product_names',
        label: '상품명',
        type: 'tags',
        required: true,
        maxItems: 5,
      },
      {
        key: 'styling_context',
        label: '스타일링 상황',
        type: 'textarea',
        required: true,
        placeholder: '예: 비즈니스 캐주얼 출근룩, 편안한 홈웨어, 여름 휴가룩',
      },
      {
        key: 'target_gender',
        label: '타겟 성별',
        type: 'select',
        options: ['여성', '남성', '유니섹스'],
      },
      {
        key: 'season',
        label: '시즌',
        type: 'select',
        options: ['봄/여름', '가을/겨울', '올시즌'],
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
      { key: 'model_image', label: '모델 이미지 (선택)', type: 'file' },
    ],
  },
  {
    key: 'webtoon_lettering',
    title: '웹툰 식자 최적화',
    comment:
      '웹툰 이미지의 텍스트를 자동 번역하고 말풍선 크기 및 폰트를 최적화하여 현지화 이미지를 생성합니다.',
    imgSrc: template_translation,
    aiStatus: 'available',
    aiFeature: 'webtoon-lettering',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '웹툰 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'source_lang',
        label: '원본 언어',
        type: 'select',
        required: true,
        options: ['한국어', '영어', '일본어', '중국어'],
      },
      {
        key: 'target_lang',
        label: '번역 언어',
        type: 'select',
        required: true,
        options: ['영어', '일본어', '중국어', '스페인어', '한국어'],
      },
      {
        key: 'genre',
        label: '장르',
        type: 'select',
        options: ['로맨스', '액션', '판타지', '일상', '공포'],
      },
      {
        key: 'font_auto_match',
        label: '폰트 자동 매칭',
        type: 'toggle',
        defaultValue: 'true',
      },
      {
        key: 'balloon_resize',
        label: '말풍선 크기 조정',
        type: 'toggle',
        defaultValue: 'true',
      },
    ],
  },
  {
    key: 'infographic_data',
    title: '프로모션 인포그래픽',
    comment:
      '상품 데이터를 기반으로 전단지, 배너, 카드뉴스 등 프로모션용 인포그래픽 이미지를 자동 생성합니다.',
    imgSrc: template_infographic,
    aiStatus: 'available',
    aiFeature: 'infographic-data',
    isLike: false,
    fields: [
      {
        key: 'products_excel',
        label: '상품 데이터 (엑셀)',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'source_images',
        label: '제품 이미지',
        type: 'files',
      },
      {
        key: 'brand_name',
        label: '브랜드명',
        type: 'text',
        placeholder: '예: Samsung',
      },
      {
        key: 'layout_type',
        label: '레이아웃',
        type: 'select',
        required: true,
        options: ['전단지', '가로형 배너', '카드뉴스', '디스플레이 광고'],
      },
      {
        key: 'promo_theme',
        label: '프로모션 테마',
        type: 'select',
        required: true,
        options: ['할인/세일', '신상품', '이벤트', '베스트셀러'],
      },
      {
        key: 'headline',
        label: '헤드라인',
        type: 'text',
        placeholder: '예: 여름 특가 최대 50% 할인',
      },
      {
        key: 'promo_period',
        label: '프로모션 기간',
        type: 'text',
        placeholder: '예: 6.1 ~ 6.30',
      },
      {
        key: 'cta_text',
        label: 'CTA 문구',
        type: 'text',
        placeholder: '예: 지금 바로 구매',
      },
      {
        key: 'brand_color',
        label: '브랜드 컬러',
        type: 'text',
        placeholder: '예: #FF0000',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'infographic_pdf',
    title: '스토리보드 슬라이드',
    comment:
      'PDF 파일을 업로드하면 각 페이지를 시각적 슬라이드 이미지로 자동 변환합니다.',
    imgSrc: template_infographic,
    aiStatus: 'available',
    aiFeature: 'infographic-pdf',
    isLike: false,
    fields: [
      {
        key: 'pdf_file',
        label: 'PDF 파일',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'output_style',
        label: '출력 스타일',
        type: 'select',
        options: ['프레젠테이션', '소셜미디어', '포스터'],
      },
      {
        key: 'color_theme',
        label: '컬러 테마',
        type: 'select',
        options: ['밝은 계열', '어두운 계열', '브랜드 컬러 유지'],
      },
    ],
  },
  {
    key: 'infographic',
    title: '인포그래픽',
    comment:
      '제품 설명서, 홍보물, 분석 리포트 등 핵심 정보를 시각화한 이미지 생성',
    imgSrc: template_infographic,
    aiStatus: 'planned',
    aiFeature: 'planned',
    isLike: true,
    fields: [
      {
        key: 'source_images',
        label: '타겟 이미지',
        type: 'files',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'topic',
        label: '주제',
        type: 'text',
        required: true,
        placeholder: '예: 2026 상반기 매출 분석',
      },
      {
        key: 'key_metrics',
        label: '핵심 지표',
        type: 'textarea',
        required: true,
        placeholder: '지표명을 줄바꿈으로 입력해 주세요.',
      },
      { key: 'target_audience', label: '대상 독자', type: 'tags', maxItems: 5 },
      {
        key: 'visual_tone',
        label: '비주얼 톤',
        type: 'text',
        placeholder: '예: 신뢰감 있는 B2B 리포트 스타일',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'illustration',
    title: '삽화',
    comment:
      '뉴스, 웹소설 등 텍스트 기반 콘텐츠의 주제와 문맥을 반영한 대표 이미지 생성',
    imgSrc: template_art,
    aiStatus: 'planned',
    aiFeature: 'planned',
    isLike: false,
    fields: [
      {
        key: 'source_images',
        label: '타겟 이미지',
        type: 'files',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'source_text',
        label: '원문 텍스트',
        type: 'textarea',
        required: true,
        placeholder: '기사/본문 핵심 내용을 붙여넣어 주세요.',
      },
      {
        key: 'genre',
        label: '장르',
        type: 'select',
        options: ['뉴스', '에세이', '웹소설', '브랜드 스토리'],
      },
      {
        key: 'mood',
        label: '분위기',
        type: 'text',
        placeholder: '예: 긴장감, 따뜻함, 희망적',
      },
      {
        key: 'style_reference',
        label: '스타일 레퍼런스',
        type: 'textarea',
        placeholder: '원하는 일러스트 스타일을 설명해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'illustration_finish',
    title: '일러스트',
    comment:
      '의상 디자인, 웹툰 스케치 등 이미지 기반 작업을 채색 및 완성된 일러스트로 변환',
    imgSrc: template_illustration,
    aiStatus: 'planned',
    aiFeature: 'planned',
    isLike: false,
    fields: [
      {
        key: 'sketch_image',
        label: '타겟 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'color_style',
        label: '채색 스타일',
        type: 'text',
        required: true,
        placeholder: '예: 셀 셰이딩, 수채화, 반실사',
        withRef: true,
      },
      {
        key: 'line_preserve',
        label: '선화 보존 수준',
        type: 'select',
        options: ['높음', '중간', '낮음'],
      },
      {
        key: 'feedback',
        label: '보정 지시',
        type: 'textarea',
        placeholder: '질감, 그림자, 디테일 보강 요청을 입력해 주세요.',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        required: true,
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'perspective_transform',
    title: 'AI 시점 변환',
    comment:
      '인테리어 렌더링 이미지의 카메라 각도, 기울기, 줌을 조정하여 새로운 시점의 실사 이미지를 생성합니다.',
    imgSrc: template_studio,
    aiStatus: 'available',
    aiFeature: 'perspective-transform',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '방 렌더링 이미지',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'view_type',
        label: '이미지 유형',
        type: 'select',
        required: true,
        options: ['인테리어 렌더링', '외관 뷰', '평면도 시각화', '기타'],
      },
      {
        key: 'camera_horizontal',
        label: '수평 각도',
        type: 'select',
        required: true,
        options: ['정면', '좌측 45°', '우측 45°', '좌측 90°', '우측 90°'],
      },
      {
        key: 'camera_vertical',
        label: '수직 기울기',
        type: 'select',
        required: true,
        options: ['아이레벨', '위에서 아래', '아래에서 위', '버드아이 뷰'],
      },
      {
        key: 'camera_zoom',
        label: '줌 레벨',
        type: 'select',
        options: ['와이드', '표준', '클로즈업'],
      },
      {
        key: 'rendering_style',
        label: '렌더링 스타일',
        type: 'select',
        options: ['실사', '스케치', '워터컬러', '미니멀'],
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'arch_rendering',
    title: '건축 렌더링 스타일 변환',
    comment:
      '건축·인테리어 이미지의 재료, 스타일을 AI로 변환합니다. 창의적 렌더링 모드로 풍부한 디테일과 변형을 추가할 수 있습니다.',
    imgSrc: template_studio,
    aiStatus: 'available',
    aiFeature: 'arch-rendering',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '이미지 업로드',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'quality',
        label: '출력 품질',
        type: 'select',
        required: true,
        options: ['빠름 — 미리보기·반복 작업용', '최적 — 높은 품질'],
      },
      {
        key: 'creative_rendering',
        label: '창의적 렌더링',
        type: 'toggle',
        defaultValue: 'false',
      },
      {
        key: 'style_detection',
        label: '스타일 감지',
        type: 'select',
        options: ['자동 감지', '수동 선택'],
      },
      {
        key: 'style_preset',
        label: '스타일 프리셋',
        type: 'select',
        options: [
          '없음',
          '모던 미니멀',
          '스칸디나비안',
          '인더스트리얼',
          '내추럴 우드',
          '럭셔리',
          '재팬니즈',
        ],
      },
      {
        key: 'extra_elements',
        label: '추가 요소',
        type: 'text',
        placeholder:
          '선택 사항 — 루버, 석재 파사드 등 추가할 요소를 입력하세요.',
      },
      {
        key: 'prompt',
        label: '추가 프롬프트',
        type: 'textarea',
        placeholder:
          '디자인을 안내할 추가 프롬프트를 입력하세요. (최대 1000자)',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'arch_elements',
    title: '렌더링 요소 추가',
    comment:
      '건축 렌더링 이미지에 사람, 차량, 녹지, 조명, 날씨 등 요소를 AI로 자연스럽게 추가합니다.',
    imgSrc: template_studio,
    aiStatus: 'available',
    aiFeature: 'arch-elements',
    isLike: false,
    fields: [
      {
        key: 'source_image',
        label: '이미지 업로드',
        type: 'file',
        required: true,
        isTargetImage: true,
      },
      {
        key: 'quality',
        label: '출력 품질',
        type: 'select',
        required: true,
        options: ['빠름 — 미리보기·반복 작업용', '최적 — 높은 품질'],
      },
      {
        key: 'elements',
        label: '추가할 요소',
        type: 'tags',
        required: true,
        options: [
          '🤖 자동',
          '👥 사람',
          '🚗 차량',
          '🌳 녹지',
          '⛲ 수경 시설',
          '🚶 보도',
          '🏙️ 도시 요소',
          '💡 조명',
          '🌤️ 날씨',
          '💨 움직임',
        ],
      },
      {
        key: 'precision_mode',
        label: '정밀 모드 (입력에 정확하게 일치)',
        type: 'toggle',
        defaultValue: 'false',
      },
      {
        key: 'reference_images',
        label: '참조 이미지 (최대 4개)',
        type: 'files',
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
  {
    key: 'floor_plan',
    title: '평면도 생성',
    comment:
      '총 면적과 방 구성, 배치 선호도를 입력하면 AI가 최적화된 평면도 이미지를 자동 생성합니다.',
    imgSrc: template_detail,
    aiStatus: 'available',
    aiFeature: 'floor-plan',
    isLike: false,
    fields: [
      {
        key: 'total_area',
        label: '총 면적',
        type: 'text',
        required: true,
        placeholder: '예: 75',
      },
      {
        key: 'area_unit',
        label: '면적 단위',
        type: 'select',
        required: true,
        options: ['미터법 (㎡)', '야드파운드법 (ft²)'],
      },
      {
        key: 'shape',
        label: '평면 형태',
        type: 'select',
        options: ['사각형', 'L자형', 'T자형', 'U자형', '기타'],
      },
      {
        key: 'rooms',
        label: '방 구성',
        type: 'tags',
        required: true,
        options: [
          '거실',
          '주방',
          '다이닝룸',
          '안방',
          '침실',
          '욕실',
          '화장실',
          '세탁실',
          '서재',
          '드레스룸',
          '현관',
          '발코니',
        ],
      },
      {
        key: 'layout_preference',
        label: '배치 선호도',
        type: 'textarea',
        placeholder:
          '선택 사항: 추가 배치 선호도, 방 간 인접 관계, 방향, 동선 또는 특별 요구사항을 입력하세요.\n예: 주방은 다이닝룸 가까이에 두고, 안방은 조용한 쪽에 배치',
      },
      {
        key: 'quality',
        label: '출력 품질',
        type: 'select',
        required: true,
        options: ['빠름 — 미리보기·반복 작업용', '최적 — 높은 품질'],
      },
      {
        key: 'floor_plan_style',
        label: '평면도 스타일',
        type: 'select',
        options: [
          '기술적 스타일',
          '건축 도면',
          '인테리어 시각화',
          '컬러 다이어그램',
        ],
      },
      {
        key: 'size',
        label: '사이즈',
        type: 'select',
        options: COMMON_SIZE_OPTIONS,
      },
    ],
  },
];

export const TARGET_KEYWORDS = [
  '20대 여성',
  '30대 직장인',
  '40대 부모',
  'MZ세대',
  '시니어',
];

export const DEFAULT_TEMPLATE_KEY = 'sns_marketing';
